## Motivation

```{r}
library(lattice)
opts_chunk$set(dpi = 144)
#opts_chunk$set(fig.width = 10)
#lattice.options(default.args = list(as.table = TRUE))
lattice.options(default.theme = standard.theme)
```

```{r}
iris$X <- iris$Sepal.Length + rnorm(nrow(iris))
```

```{r splom, dev="png"}
splom(~ iris[-5])
```

```{r reference, dev="png"}
plot(xyplot(Sepal.Length ~ X, data = iris, groups = Species, ylim = range(iris[-5])), split = c(1, 1, 2, 2), more = TRUE)
plot(xyplot(Sepal.Width ~ X, data = iris, groups = Species, ylim = range(iris[-5])), split = c(2, 1, 2, 2), more = TRUE)
plot(xyplot(Petal.Length ~ X, data = iris, groups = Species, ylim = range(iris[-5])), split = c(1, 2, 2, 2), more = TRUE)
plot(xyplot(Petal.Width ~ X, data = iris, groups = Species, ylim = range(iris[-5])), split = c(2, 2, 2, 2), more = TRUE)
```

Reshape by Measure(ment) and then Flower part
```{r}
iris.M <-
    reshape(iris, direction = "long",
            varying = list(c("Sepal.Length", "Sepal.Width"), c("Petal.Length", "Petal.Width")),
            v.names = c("Sepal", "Petal"),
            timevar = "Measure", times = c("Length", "Width"),
            idvar = "id1")
iris.l.M <-
    reshape(iris.M, direction = "long",
            varying = c("Sepal", "Petal"), v.names = "Y",
            timevar = "Flower.part", times = c("Sepal", "Petal"),
            drop = "id1")
```

```{r correct.M, dev="png"}
xyplot(Y ~ X | Measure * Flower.part, data = iris.l.M, groups = Species)
```

Reshape by Flower part and then by Measure
```{r}
iris.F <-
    reshape(iris, direction = "long",
            varying = list(c("Sepal.Length", "Petal.Length"), c("Sepal.Width", "Petal.Width")),
            v.names = c("Length", "Width"),
            timevar = "Flower.part", times = c("Sepal", "Petal"),
            idvar = "id1")
iris.l.F <-
    reshape(iris.F, direction = "long",
            varying = c("Length", "Width"), v.names = "Y",
            timevar = "Measure", times = c("Length", "Width"),
            drop = "id1")
```

```{r correct.F, dev="png"}
xyplot(Y ~ X | Measure * Flower.part, data = iris.l.F, groups = Species)
```

