# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R you experienced?
email: attila.gulyas.kovacs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog on programming techniques and statistical modeling using the R language
baseurl: "/R-you-experienced" # the subpath of your site, e.g. /blog
url: "https://attilagk.github.io" # the base hostname & protocol for your site
github_username:  attilagk

# Build settings
markdown: kramdown
#theme: jekyll-theme-merlot
theme: jekyll-theme-leap-day
permalink: /:categories/:year-:month-:day-:title.html
